Create a new switch for configuring an already deployed image

diff --git a/Linux/flash b/Linux/flash
--- a/Linux/flash
+++ b/Linux/flash
@@ -24,6 +24,7 @@ OPTIONS:
   --help|-h       Show this message
   --bootconf|-C   Copy this config file to /boot/config.txt
   --config|-c     Copy this config file to /boot/device-init.yaml (or occidentalis.txt)
+  --onlyconf|-o   Configure an already written image (useful for testing)
   --hostname|-n   Set hostname for this SD image
   --ssid|-s       Set WiFi SSID for this SD image
   --password|-p   Set WiFI password for this SD image
@@ -92,7 +93,7 @@ done
 # reset the translated args
 eval set -- "$args"
 # now we can process with getopt
-while getopts ":hc:n:s:p:C:l:d:u:m:" opt; do
+while getopts ":hc:n:s:p:C:l:d:u:m:o" opt; do
   case $opt in
     h)  usage ;;
     c)  CONFIG_FILE=$OPTARG ;;
@@ -104,6 +105,7 @@ while getopts ":hc:n:s:p:C:l:d:u:m:" opt; do
     d)  DEVICE=$OPTARG ;;
     u)  USER_DATA=$OPTARG ;;
     m)  META_DATA=$OPTARG ;;
+    o)  CONFIGURE_ONLY=1 ;;
     \?) usage ;;
     :)
       echo "option -$OPTARG requires an argument"
@@ -157,39 +159,41 @@ if [ ! -z "${CONFIG_FILE}" ]; then
   fi
 fi
 
-if [ -f "/tmp/${filename}" ]; then
-  image=/tmp/${filename}
-  echo "Using cached image ${image}"
-elif [ -f "/tmp/${filename}.img" ]; then
-   image=/tmp/${filename}.img
-   echo "Using cached image ${image}"
-else
-  if beginswith http:// "${image}" || beginswith https:// "${image}"; then
-    which curl 2>/dev/null || error "Error: curl not found. Aborting" 1
-    echo "Downloading ${image} ..."
-    curl -L --fail -o "/tmp/image.img.${extension}" "${image}"
-    image=/tmp/image.img.${extension}
-  fi
+if [[ -z $CONFIGURE_ONLY ]] ; then
+  if [ -f "/tmp/${filename}" ]; then
+    image=/tmp/${filename}
+    echo "Using cached image ${image}"
+  elif [ -f "/tmp/${filename}.img" ]; then
+    image=/tmp/${filename}.img
+    echo "Using cached image ${image}"
+  else
+    if beginswith http:// "${image}" || beginswith https:// "${image}"; then
+      which curl 2>/dev/null || error "Error: curl not found. Aborting" 1
+      echo "Downloading ${image} ..."
+      curl -L --fail -o "/tmp/image.img.${extension}" "${image}"
+      image=/tmp/image.img.${extension}
+    fi
 
-  if beginswith s3:// "${image}" ;then
-    which aws 2>/dev/null || error "Error: aws not found. Aborting" 1
-    echo "Downloading ${image} ..."
-    aws s3 cp "${image}" "/tmp/image.img.${extension}"
-    image=/tmp/image.img.${extension}
-  fi
+    if beginswith s3:// "${image}" ;then
+      which aws 2>/dev/null || error "Error: aws not found. Aborting" 1
+      echo "Downloading ${image} ..."
+      aws s3 cp "${image}" "/tmp/image.img.${extension}"
+      image=/tmp/image.img.${extension}
+    fi
 
-  if [ ! -f "${image}" ]; then
-    echo "File not found."
-    exit 10
-  fi
+    if [ ! -f "${image}" ]; then
+      echo "File not found."
+      exit 10
+    fi
 
-  if [[ "$(file "${image}")" == *"Zip archive"* ]]; then
-    which unzip 2>/dev/null || error "Error: unzip not found. Aborting" 1
-    echo "Uncompressing ${image} ..."
-    unzip -o "${image}" -d /tmp
-    image=$(unzip -l "${image}" | grep -v Archive: | grep img | awk 'NF>1{print $NF}')
-    image="/tmp/${image}"
-    echo "Use ${image}"
+    if [[ "$(file "${image}")" == *"Zip archive"* ]]; then
+      which unzip 2>/dev/null || error "Error: unzip not found. Aborting" 1
+      echo "Uncompressing ${image} ..."
+      unzip -o "${image}" -d /tmp
+      image=$(unzip -l "${image}" | grep -v Archive: | grep img | awk 'NF>1{print $NF}')
+      image="/tmp/${image}"
+      echo "Use ${image}"
+    fi
   fi
 fi
 
@@ -254,22 +258,24 @@ while true; do
   fi
 done
 
-echo "Flashing ${image} to ${disk} ..."
-if [[ -x $(which pv) ]]; then
-  # this sudo here is used for a login without pv's progress bar
-  # hiding the password prompt
-  size=$(sudo stat -c %s "${image}")
-  pv -s "${size}" < "${image}" | sudo dd bs=1M "of=${disk}"
-else
-  echo "No 'pv' command found, so no progress available."
-  echo "Press CTRL+T if you want to see the current info of dd command."
-  sudo dd bs=1M "if=${image}" "of=${disk}"
+if [[ -z $CONFIGURE_ONLY ]] ; then
+  echo "Flashing ${image} to ${disk} ..."
+  if [[ -x $(which pv) ]]; then
+    # this sudo here is used for a login without pv's progress bar
+    # hiding the password prompt
+    size=$(sudo stat -c %s "${image}")
+    pv -s "${size}" < "${image}" | sudo dd bs=1M "of=${disk}"
+  else
+    echo "No 'pv' command found, so no progress available."
+    echo "Press CTRL+T if you want to see the current info of dd command."
+    sudo dd bs=1M "if=${image}" "of=${disk}"
+  fi
+
+  echo "Waiting for device..."
+  udevadm settle
+
+  sudo hdparm -z "${disk}"
 fi
-
-echo "Waiting for device..."
-udevadm settle
-
-sudo hdparm -z "${disk}"
 
 echo "Mounting Disk"
 boot=/tmp/mnt.$$
